### ISSUE TITLE
Can you publish this to npm?

### ISSUE THREAD

**Issue by RobertMenke** [andywer/jquery-dim-background#4]
Thanks for the hard word on the plugin. I was wondering if you could publish this to npm so that we can manage this with the rest of our node_modules dependencies. Thanks!

**Comment by andywer** [comment]
Hi @RobertMenke. Done ;)

This jQuery plugin is alreay so old, I think nobody used `npm` to manage frontend dependencies at the time... ^^

Cheers

**Comment by cyorobert** [comment]
Awesome - thanks! The plugin still works great :)
