### ISSUE TITLE
listen for click events on $curtain

### ISSUE THREAD

**Issue by TSMMark** [andywer/jquery-dim-background#6]
hi i would like to listen for click events on the curtain element and then close the curtain when clicked.

**Comment by TSMMark** [comment]
Any advice for implementing this? I can submit a PR in no time

**Comment by andywer** [comment]
Hey! You should be able to just do `$('#dimbackground-curtain').click(...)` to attach the click listener.

**Comment by TSMMark** [comment]
I would say that's not 100% ideal but it will certainly work. Thanks!

**Comment by andywer** [comment]
True, but look how old the repository is. My willingness to change it after so many years is quite low... 😅

**Comment by TSMMark** [comment]
It's the only package I could find that does something like this! I really wanted a react component package, but I was going to settle for making a custom react wrapper around this jquery package to start. Thanks again!
